apiVersion: v1
kind: ConfigMap
metadata:
  name: zeppelin-server-conf-map
data:
  #zeppelin config
  SERVICE_DOMAIN: local.zeppelin-project.org:8087
  ZEPPELIN_K8S_CONTAINER_IMAGE: {{ .Values.zeppelin.image }}
  ZEPPELIN_HOME: /zeppelin
  ZEPPELIN_SERVER_RPC_PORTRANGE: 12320:12320
  #spark config
  ZEPPELIN_K8S_SPARK_CONTAINER_IMAGE: {{ .Values.spark.image }}
  SPARK_MASTER: k8s://https://kubernetes.default:443
  SPARK_HOME: /spark
  SPARK_CONF_DIR: /opt/spark/conf
  #notebook s3 Path
  ZEPPELIN_NOTEBOOK_S3_USER: {{ .Values.zeppelin.noteBookS3User }}
  ZEPPELIN_NOTEBOOK_S3_BUCKET: {{ .Values.zeppelin.noteBookS3Bucket }}
  ZEPPELIN_NOTEBOOK_S3_ENDPOINT: s3.amazonaws.com
  # spark driver host
  ZEPPELIN_K8S_ENGINEPLUS_INGRESS_ENABLED: '{{ .Values.ingress.enabled }}'
  ZEPPELIN_K8S_ENGINEPLUS_INGRESS: {{ .Values.ingress.suffix }}

  shiro.ini: |-
    [users]
    admin = {{ .Values.zeppelin.password }}, admin

    [main]
    sessionManager = org.apache.shiro.web.session.mgt.DefaultWebSessionManager
    cookie = org.apache.shiro.web.servlet.SimpleCookie
    cookie.name = JSESSIONID
    cookie.httpOnly = true
    sessionManager.sessionIdCookie = $cookie
    securityManager.sessionManager = $sessionManager
    securityManager.sessionManager.globalSessionTimeout = 86400000
    shiro.loginUrl = /api/login

    [roles]
    admin = *

    [urls]
    /api/version = anon
    /api/cluster/address = anon
    /api/interpreter/setting/restart/** = authc
    /api/interpreter/** = authc, roles[admin]
    /api/notebook-repositories/** = authc, roles[admin]
    /api/configurations/** = authc, roles[admin]
    /api/credential/** = authc, roles[admin]
    /api/admin/** = authc, roles[admin]
    /** = authc
  zeppelin-site.xml: |-
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

    <configuration>
      <property>
          <name>zeppelin.cluster.addr</name>
          <value></value>
          <description>Server cluster address, eg. 127.0.0.1:6000,127.0.0.2:6000,127.0.0.3:6000</description>
      </property>

      <property>
          <name>zeppelin.server.addr</name>
          <value>0.0.0.0</value>
          <description>Server binding address</description>
      </property>

      <property>
          <name>zeppelin.server.port</name>
          <value>8087</value>
          <description>Server port.</description>
      </property>

      <property>
          <name>zeppelin.server.ssl.port</name>
          <value>8443</value>
          <description>Server ssl port. (used when ssl property is set to true)</description>
      </property>

      <property>
          <name>zeppelin.server.context.path</name>
          <value>/</value>
          <description>Context Path of the Web Application</description>
      </property>

      <property>
          <name>zeppelin.war.tempdir</name>
          <value>webapps</value>
          <description>Location of jetty temporary directory</description>
      </property>

      <property>
          <name>zeppelin.interpreter.include</name>
          <value></value>
          <description>All the inteprreters that you would like to include. You can only specify either 'zeppelin.interpreter.include' or 'zeppelin.interpreter.exclude'. Specifying them together is not allowed.</description>
      </property>

      <property>
          <name>zeppelin.interpreter.exclude</name>
          <value></value>
          <description>All the inteprreters that you would like to exclude. You can only specify either 'zeppelin.interpreter.include' or 'zeppelin.interpreter.exclude'. Specifying them together is not allowed.</description>
      </property>

      <property>
          <name>zeppelin.notebook.homescreen</name>
          <value></value>
          <description>id of notebook to be displayed in homescreen. ex) 2A94M5J1Z Empty value displays default home screen</description>
      </property>

      <property>
          <name>zeppelin.notebook.homescreen.hide</name>
          <value>false</value>
          <description>hide homescreen notebook from list when this value set to true</description>
      </property>

      <property>
          <name>zeppelin.notebook.collaborative.mode.enable</name>
          <value>true</value>
          <description>Enable collaborative mode</description>
      </property>

      <property>
          <name>zeppelin.notebook.dir</name>
          <value>notebook</value>
          <description>path or URI for notebook persist</description>
      </property>

      <property>
          <name>zeppelin.notebook.s3.timeout</name>
          <value>120000</value>
          <description>s3 bucket endpoint request timeout in msec.</description>
      </property>

      <property>
          <name>zeppelin.notebook.storage</name>
          <value>org.apache.zeppelin.notebook.repo.S3NotebookRepo</value>
          <description>notebook persistence layer implementation</description>
      </property>

      <property>
          <name>zeppelin.notebook.one.way.sync</name>
          <value>false</value>
          <description>If there are multiple notebook storages, should we treat the first one as the only source of truth?</description>
      </property>

      <property>
          <name>zeppelin.interpreter.dir</name>
          <value>interpreter</value>
          <description>Interpreter implementation base directory</description>
      </property>

      <property>
          <name>zeppelin.interpreter.localRepo</name>
          <value>local-repo</value>
          <description>Local repository for interpreter's additional dependency loading</description>
      </property>

      <property>
          <name>zeppelin.interpreter.dep.mvnRepo</name>
          <value>https://repo1.maven.org/maven2/</value>
          <description>Remote principal repository for interpreter's additional dependency loading</description>
      </property>

      <property>
          <name>zeppelin.dep.localrepo</name>
          <value>local-repo</value>
          <description>Local repository for dependency loader</description>
      </property>

      <property>
          <name>zeppelin.interpreter.group.default</name>
          <value>spark</value>
          <description></description>
      </property>

      <property>
          <name>zeppelin.interpreter.connect.timeout</name>
          <value>300000</value>
          <description>Interpreter process connect timeout in msec.</description>
      </property>

      <property>
          <name>zeppelin.interpreter.output.limit</name>
          <value>10240000</value>
          <description>Output message from interpreter exceeding the limit will be truncated</description>
      </property>

      <property>
          <name>zeppelin.server.allowed.origins</name>
          <value>*</value>
          <description>Allowed sources for REST and WebSocket requests (i.e. http://onehost:8080,http://otherhost.com). If you leave * you are vulnerable to https://issues.apache.org/jira/browse/ZEPPELIN-173</description>
      </property>

      <property>
          <name>zeppelin.username.force.lowercase</name>
          <value>ture</value>
          <description>Force convert username case to lower case, useful for Active Directory/LDAP. Default is not to change case</description>
      </property>

      <property>
          <name>zeppelin.notebook.default.owner.username</name>
          <value></value>
          <description>Set owner role by default</description>
      </property>

      <property>
          <name>zeppelin.notebook.public</name>
          <value>private</value>
          <description>Make notebook public by default when created, private otherwise</description>
      </property>

      <property>
          <name>zeppelin.websocket.max.text.message.size</name>
          <value>10240000</value>
          <description>Size in characters of the maximum text message to be received by websocket. Defaults to 10240000</description>
      </property>

      <property>
          <name>zeppelin.server.default.dir.allowed</name>
          <value>false</value>
          <description>Enable directory listings on server.</description>
      </property>

      <property>
          <name>zeppelin.interpreter.lifecyclemanager.class</name>
          <value>org.apache.zeppelin.interpreter.lifecycle.TimeoutLifecycleManager</value>
          <description>LifecycleManager class for managing the lifecycle of interpreters, by default interpreter will
          be closed after timeout</description>
      </property>

      <property>
          <name>zeppelin.interpreter.lifecyclemanager.timeout.checkinterval</name>
          <value>600000</value>
          <description>Milliseconds of the interval to checking whether interpreter is time out</description>
      </property>

      <property>
          <name>zeppelin.interpreter.lifecyclemanager.timeout.threshold</name>
          <value>10800000</value>
          <description>Milliseconds of the interpreter timeout threshold, by default it is 1 hour</description>
      </property>

      <property>
          <name>zeppelin.server.jetty.name</name>
          <value> </value>
          <description>Hardcoding Application Server name to Prevent Fingerprinting</description>
      </property>

      <property>
          <name>zeppelin.server.jetty.thread.pool.max</name>
          <value>4000</value>
          <description>Max Thread pool number for QueuedThreadPool in Jetty Server</description>
      </property>

      <property>
          <name>zeppelin.server.jetty.thread.pool.min</name>
          <value>10</value>
          <description>Min Thread pool number for QueuedThreadPool in Jetty Server</description>
      </property>

      <property>
          <name>zeppelin.server.jetty.thread.pool.timeout</name>
          <value>300</value>
          <description>Timeout number for QueuedThreadPool in Jetty Server</description>
      </property>

      <property>
          <name>zeppelin.server.xframe.options</name>
          <value>SAMEORIGIN</value>
          <description>The X-Frame-Options HTTP response header can be used to indicate whether or not a browser should be allowed to render a page in a frame/iframe/object.</description>
      </property>

      <property>
          <name>zeppelin.server.xxss.protection</name>
          <value>1; mode=block</value>
          <description>The HTTP X-XSS-Protection response header is a feature of Internet Explorer, Chrome and Safari that stops pages from loading when they detect reflected cross-site scripting (XSS) attacks. When value is set to 1 and a cross-site scripting attack is detected, the browser will sanitize the page (remove the unsafe parts).</description>
      </property>

      <property>
          <name>zeppelin.server.xcontent.type.options</name>
          <value>nosniff</value>
          <description>The HTTP X-Content-Type-Options response header helps to prevent MIME type sniffing attacks. It directs the browser to honor the type specified in the Content-Type header, rather than trying to determine the type from the content itself. The default value "nosniff" is really the only meaningful value. This header is supported on all browsers except Safari and Safari on iOS.</description>
      </property>

      <property>
          <name>zeppelin.notebook.cron.enable</name>
          <value>true</value>
          <description>Notebook enable cron scheduler feature</description>
      </property>

      <property>
          <name>zeppelin.notebook.cron.folders</name>
          <value> </value>
          <description>Notebook cron folders</description>
      </property>

      <property>
          <name>zeppelin.run.mode</name>
          <value>auto</value>
          <description>'auto|local|k8s|docker'</description>
      </property>

      <property>
          <name>zeppelin.k8s.portforward</name>
          <value>false</value>
          <description>Port forward to interpreter rpc port. Set 'true' only on local development when zeppelin.k8s.mode 'on'</description>
      </property>

      <property>
          <name>zeppelin.k8s.template.dir</name>
          <value>k8s</value>
          <description>Kubernetes yaml spec files</description>
      </property>

      <property>
          <name>zeppelin.search.index.rebuild</name>
          <value>false</value>
          <description>Whether rebuild index when zeppelin start. If true, it would read all notes and rebuild the index, this would consume lots of memory if you have large amounts of notes, so by default it is false</description>
      </property>

      <property>
          <name>zeppelin.search.use.disk</name>
          <value>true</value>
          <description>Whether using disk for storing search index, if false, memory will be used instead.</description>
      </property>

      <property>
          <name>zeppelin.search.index.path</name>
          <value>/tmp/zeppelin-index</value>
          <description>path for storing search index on disk.</description>
      </property>

      <property>
          <name>zeppelin.jobmanager.enable</name>
          <value>true</value>
          <description>The Job tab in zeppelin page seems not so useful instead it cost lots of memory and affect the performance.
          Disable it can save lots of memory</description>
      </property>

      <property>
          <name>zeppelin.spark.only_yarn_cluster</name>
          <value>false</value>
          <description>Whether only allow yarn cluster mode</description>
      </property>
      <property>
          <name>zeppelin.anonymous.allowed</name>
          <value>false</value>
          <description>Anonymous user allowed by default</description>
      </property>
    </configuration>