kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zeppelin-server-role
rules:
  - apiGroups: ["", "extensions"]
    resources: ["pods", "services", "configmaps", "ingresses"]
    verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs:
      ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]
