{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  labels:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    helm.sh/chart: {{ include "spark-history-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

type: Opaque
data:
  auth: {{ htpasswd "admin" .Values.ingress.auth.password | b64enc | quote }}
{{- end -}}